### DISCUSSION TITLE
Go AWS SDK V2 - Error in Deploying to AWS Lambda

### DISCUSSION THREAD

**Discussion by dmitrimahayana** [aws/aws-sdk-go-v2#2719] [Q&A]
Hi All,

Currently, I am deploying my golang to AWS Lambda using sam build with go version is `go1.23rc2 windows/amd64`.
But it always fails in the build process with error:
```
/go/pkg/mod/github.com/aws/aws-sdk-go-v2/credentials@v1.17.27/endpointcreds/internal/client/middleware.go:114:14: undefined: io.ReadAll
note: module requires Go 1.20
# github.com/aws/aws-sdk-go-v2/internal/middleware
/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.30.3/internal/middleware/middleware.go:16:10: undefined: atomic.Int64
note: module requires Go 1.20
# github.com/aws/aws-sdk-go-v2/internal/ini
/go/pkg/mod/github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/ini.go:44:19: undefined: io.ReadAll
/go/pkg/mod/github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/strings.go:8:13: undefined: strings.Cut
/go/pkg/mod/github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/strings.go:9:12: undefined: strings.Cut
/go/pkg/mod/github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/strings.go:14:13: undefined: strings.Cut
/go/pkg/mod/github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/strings.go:15:12: undefined: strings.Cut
/go/pkg/mod/github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/strings.go:16:12: undefined: strings.Cut
/go/pkg/mod/github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/strings.go:17:12: undefined: strings.Cut
/go/pkg/mod/github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/strings.go:30:14: undefined: strings.Cut
note: module requires Go 1.20
# github.com/aws/smithy-go/private/requestcompression
/go/pkg/mod/github.com/aws/smithy-go@v1.20.3/private/requestcompression/gzip.go:17:18: undefined: io.ReadAll
note: module requires Go 1.20
```

This is my go.mod:
```
module go_sm_object_value_update

// go 1.23rc2 // Local Run
go 1.23 // AWS Lambda Run

require (
	github.com/aws/aws-lambda-go v1.47.0 // indirect
	github.com/aws/aws-sdk-go-v2 v1.30.3 // indirect
	github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.6.3 // indirect
	github.com/aws/aws-sdk-go-v2/config v1.27.27 // indirect
	github.com/aws/aws-sdk-go-v2/credentials v1.17.27 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.16.11 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.3.15 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.6.15 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.8.0 // indirect
	github.com/aws/aws-sdk-go-v2/internal/v4a v1.3.15 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.11.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.3.17 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.11.17 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.17.15 // indirect
	github.com/aws/aws-sdk-go-v2/service/s3 v1.58.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.22.4 // indirect
	github.com/aws/aws-sdk-go-v2/service/ssooidc v1.26.4 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.30.3 // indirect
	github.com/aws/smithy-go v1.20.3 // indirect
	github.com/jmespath/go-jmespath v0.4.0 // indirect
)
```

And this is my lambda folder structure:
![image](https://github.com/user-attachments/assets/efcdae2e-8c98-489f-9e88-3fed1dfb8f4b)

I follow this guide (https://docs.aws.amazon.com/lambda/latest/dg/golang-package.html) to create template.yaml.
This is the template.yaml:
```
  GoSmObjectValueUpdatev2:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Join [ '_', [ 'go_sm_object_value_update', !Ref PhokusEnvironment ] ]
      Description: 'Lambda to prepare input media posts for IR'
      # CodeUri: lambda_functions/social/v2/go_sm_object_value_update/build/bootstrap.zip  # Ensure this path is correct
      CodeUri: lambda_functions/social/v2/go_sm_object_value_update/ # folder where your main program resides
      Handler: bootstrap
      Runtime: provided.al2023
      # Architectures: [arm64]
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 900
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - lambda:InvokeFunction
              Resource:
                - !Join [ '', [ 'arn:aws:s3:::', !FindInMap [ PhokusEnvironmentMapping, !Ref PhokusEnvironment, SmConfigurationBucket ], '/*' ] ]
      Environment:
        Variables:
          SM_CONFIGURATION_BUCKET: !FindInMap [ PhokusEnvironmentMapping, !Ref PhokusEnvironment, SmConfigurationBucket ]
```

Please help if you find the issue in my code.
